### ISSUE TITLE
The dark mode button is not toggling in the sign-in and sign-up page[GSSOC'23]

### ISSUE THREAD

**Issue by huzaifa9999** [MonalikaPatnaik/UMatter#476]
The light and dark mode button is working but it is not toggling , the icon indicates only dark mode , irrespective of it being in light mode .

![Screenshot (182)](https://github.com/MonalikaPatnaik/UMatter/assets/97234805/0e51da0e-96af-4127-8832-ea2e15699827)

**Comment by VijayalakshmiGanesh** [comment]
I will do signup toggle mode functionality work same as sign in page. Could you please assign me this issue under GSSoC'23

**Comment by MonalikaPatnaik** [comment]
Hey..i think similar issue is been assigned..will assign if it was not done!

**Comment by huzaifa9999** [comment]
> Hey..i think similar issue is been assigned..will assign if it was not done!

yeah sure , will wait for the reply 🤞

**Comment by huzaifa9999** [comment]
> Hey..i think similar issue is been assigned..will assign if it was not done!

Hii @MonalikaPatnaik I again checked it and the issue is still there , Ig I can now be assigned and work on it.

**Comment by MonalikaPatnaik** [comment]
Heyy could u pls check it again..i think it's been fixed now!

**Comment by huzaifa9999** [comment]
> Heyy could u pls check it again..i think it's been fixed now!

Umm hi ! I again checked just now on the side , its still the same unfortunately. I am attaching screenshots , where signin page is in lightmode but the icon is stuck on dark mode . Have a look at it @MonalikaPatnaik 
![Screenshot (191)](https://github.com/MonalikaPatnaik/UMatter/assets/97234805/ab81ee41-4deb-4c9a-b8eb-1b212c52035e)

**Comment by MonalikaPatnaik** [comment]
Okok pls fix it then!
